data_harmonization_inputs:
  regions : ["MI-01","NY-01"]
  min_year : 2022
  max_year : 2026

general_inputs :
  dependent_variable : NO_OF_NEW_JOINEES
  date_var : START_OF_WEEK
  date_format_pyspark : "yyyy-MM-dd"
  date_format_pandas : "yyyy-MM-dd"
  modeling_granularity : ["REGIONNAME","F_CODE"]
  output_database : ORANGE_ZONE_SBX_TA
  output_schema : PUBLIC

data_processing :
  outlier_treatment_needed : yes #yes/no
  outlier_treatment :
    algorithm : inter_quartile_range
    hampel_filter :
      window_size : 2
      no_of_sigmas : 3
    inter_quartile_range :
      minimum_quantile : 5
      maximum_quantile : 95
  
  standardization_needed : yes

  missing_dates_treatment_needed : yes
  
  missing_value_treatment_needed: yes
  missing_value_treatment :
    Mean :
      cols : ["NO_OF_NEW_JOINEES"]
      zero_as_missing_value : False
    Median :
      cols : []
      zero_as_missing_value : False
    Scalar :
      cols : []
      value : 0
      zero_as_missing_value : False
    Rolling_Mean :
      cols : []
      window : 4
      zero_as_missing_value : False
    Rolling_Median :
      cols : []
      window : 4
      zero_as_missing_value : False
    Forward_fill :
      cols : ["REGIONAL_CPI","REGIONAL_UNEMPLOYMENT_RATE","HPI"]
      zero_as_missing_value : False
    Backward_fill :
      cols : []
      zero_as_missing_value : False
    Linear_Interpolation :
      cols : []
      zero_as_missing_value : False
    Spline_Interpolation :
      cols : []
      zero_as_missing_value : False
    Mode :
      cols : []
    Mean_Across_Years :
      cols : []
      time_granularity : daily
      zero_as_missing_value : False
    Zero:
      cols : ["TOTAL_SPENDS_OVERALL","PRIMED_LEADS","PROMO_WEIGHTED_MEAN","SUMMER_WEIGHTED_MEAN","AOJO_WEIGHTED_MEAN","NEWVEMBER_WEIGHTED_MEAN","RR_WEIGHTED_MEAN","WINBACK_CORP_WEIGHTED_MEAN","DECEMBER_WEIGHTED_MEAN","OTHER_WEIGHTED_MEAN","AOAO_WEIGHTED_MEAN","FOUNDER_WEIGHTED_MEAN","FMF_WEIGHTED_MEAN","NMF_WEIGHTED_MEAN","KICK_START_WEIGHTED_MEAN","FM_WEIGHTED_MEAN","DSO_WEIGHTED_MEAN","P65_WEIGHTED_MEAN","CORP_WEIGHTED_MEAN","WINBACK_WEIGHTED_MEAN","FAO_WEIGHTED_MEAN","SPRING_WEIGHTED_MEAN",
              "PROMO_WEIGHTED_MEAN_STREAK","SUMMER_WEIGHTED_MEAN_STREAK","AOJO_WEIGHTED_MEAN_STREAK","NEWVEMBER_WEIGHTED_MEAN_STREAK","RR_WEIGHTED_MEAN_STREAK","WINBACK_CORP_WEIGHTED_MEAN_STREAK","DECEMBER_WEIGHTED_MEAN_STREAK","OTHER_WEIGHTED_MEAN_STREAK","AOAO_WEIGHTED_MEAN_STREAK","FOUNDER_WEIGHTED_MEAN_STREAK","FMF_WEIGHTED_MEAN_STREAK","NMF_WEIGHTED_MEAN_STREAK","KICK_START_WEIGHTED_MEAN_STREAK","FM_WEIGHTED_MEAN_STREAK","DSO_WEIGHTED_MEAN_STREAK","P65_WEIGHTED_MEAN_STREAK","CORP_WEIGHTED_MEAN_STREAK","WINBACK_WEIGHTED_MEAN_STREAK","FAO_WEIGHTED_MEAN_STREAK","SPRING_WEIGHTED_MEAN_STREAK",
              "FMF_ACTIVE_STUDIOS_NORMALIZED","NMF_ACTIVE_STUDIOS_NORMALIZED","FM_ACTIVE_STUDIOS_NORMALIZED","KICK_START_ACTIVE_STUDIOS_NORMALIZED","FOUNDER_ACTIVE_STUDIOS_NORMALIZED","RR_ACTIVE_STUDIOS_NORMALIZED","WINBACK_CORP_ACTIVE_STUDIOS_NORMALIZED","SUMMER_ACTIVE_STUDIOS_NORMALIZED","AOJO_ACTIVE_STUDIOS_NORMALIZED","NEWVEMBER_ACTIVE_STUDIOS_NORMALIZED","OTHER_ACTIVE_STUDIOS_NORMALIZED","AOAO_ACTIVE_STUDIOS_NORMALIZED","DSO_ACTIVE_STUDIOS_NORMALIZED","PROMO_ACTIVE_STUDIOS_NORMALIZED","P65_ACTIVE_STUDIOS_NORMALIZED","CORP_ACTIVE_STUDIOS_NORMALIZED","WINBACK_ACTIVE_STUDIOS_NORMALIZED","FAO_ACTIVE_STUDIOS_NORMALIZED","SPRING_ACTIVE_STUDIOS_NORMALIZED",
              'CHRISTMAS_DAY','CHRISTMAS_DAY_OBSERVED','COLUMBUS_DAY','INDEPENDENCE_DAY','JUNETEENTH_NATIONAL_INDEPENDENCE_DAY','JUNETEENTH_NATIONAL_INDEPENDENCE_DAY_OBSERVED','LABOR_DAY','MARTIN_LUTHER_KING_JR_DAY','MEMORIAL_DAY','NEW_YEAR_S_DAY','NEW_YEAR_S_DAY_OBSERVED','THANKSGIVING_DAY','VETERANS_DAY','VETERANS_DAY_OBSERVED','WASHINGTON_S_BIRTHDAY']
      zero_as_missing_value : False

feature_engineering_details :

  lag_lead_needed: yes
  featurewise_lag_lead_dict:
    LOCAL_CAMPAIGN_LEADS : ["lag", [1, 2, 3], 0]
    TOTAL_SPENDS_OVERALL : ["lag", [1, 2], 0]
    NATIONAL_CAMPAIGN_LEADS: ["lead", [1, 2], 0]
  
  log_transformation_needed: yes
  log_transformation_features:
    - NO_OF_NEW_JOINEES

  si_needed: yes
  si_target_column: NON_PROMO_JOINS
  categorical_columns_ads:
    - REGIONNAME


feature_mapping :
  baseline_cols: ['TREND_YEAR','TREND_MONTH','TREND_QUARTER',"REGIONAL_CPI","REGIONAL_UNEMPLOYMENT_RATE","PRIMED_LEADS","HPI"]

  increment_cols: ['NATIONAL_CAMPAIGN_LEADS','LOCAL_CAMPAIGN_LEADS','REGIONAL_CAMPAIGN_LEADS','NON_WEB_CAMPAIGN_LEADS','INTRO_BOOKINGS',
                  "PROMO_WEIGHTED_MEAN","SUMMER_WEIGHTED_MEAN","AOJO_WEIGHTED_MEAN","NEWVEMBER_WEIGHTED_MEAN","FAO_WEIGHTED_MEAN","RR_WEIGHTED_MEAN","WINBACK_CORP_WEIGHTED_MEAN","DECEMBER_WEIGHTED_MEAN","OTHER_WEIGHTED_MEAN","AOAO_WEIGHTED_MEAN","P65_WEIGHTED_MEAN","HOLIDAY_WEIGHTED_MEAN","FOUNDER_WEIGHTED_MEAN","FMF_WEIGHTED_MEAN","NMF_WEIGHTED_MEAN","KICK_START_WEIGHTED_MEAN","FM_WEIGHTED_MEAN","NONE_WEIGHTED_MEAN","DSO_WEIGHTED_MEAN","CORP_WEIGHTED_MEAN","WINBACK_WEIGHTED_MEAN","SPRING_WEIGHTED_MEAN",
                  "TOTAL_SPENDS_OVERALL","TOTAL_SPENDS_OVERALL_LAG1","TOTAL_SPENDS_OVERALL_LAG2",
                  "FMF_ACTIVE_STUDIOS_NORMALIZED","NMF_ACTIVE_STUDIOS_NORMALIZED","FM_ACTIVE_STUDIOS_NORMALIZED","KICK_START_ACTIVE_STUDIOS_NORMALIZED","FOUNDER_ACTIVE_STUDIOS_NORMALIZED","RR_ACTIVE_STUDIOS_NORMALIZED","WINBACK_CORP_ACTIVE_STUDIOS_NORMALIZED","SUMMER_ACTIVE_STUDIOS_NORMALIZED","AOJO_ACTIVE_STUDIOS_NORMALIZED","NEWVEMBER_ACTIVE_STUDIOS_NORMALIZED","OTHER_ACTIVE_STUDIOS_NORMALIZED","AOAO_ACTIVE_STUDIOS_NORMALIZED","DSO_ACTIVE_STUDIOS_NORMALIZED","PROMO_ACTIVE_STUDIOS_NORMALIZED","P65_ACTIVE_STUDIOS_NORMALIZED","CORP_ACTIVE_STUDIOS_NORMALIZED","WINBACK_ACTIVE_STUDIOS_NORMALIZED","FAO_ACTIVE_STUDIOS_NORMALIZED","SPRING_ACTIVE_STUDIOS_NORMALIZED",
                  "FMF_MEAN","NMF_MEAN","FM_MEAN","KICK_START_MEAN","FOUNDER_MEAN","RR_MEAN","WINBACK_CORP_MEAN","SUMMER_MEAN","AOJO_MEAN","NEWVEMBER_MEAN","FAO_MEAN","OTHER_MEAN","AOAO_MEAN","DSO_MEAN","PROMO_MEAN",
                  "PROMO_WEIGHTED_MEAN_STREAK","SUMMER_WEIGHTED_MEAN_STREAK","AOJO_WEIGHTED_MEAN_STREAK","NEWVEMBER_WEIGHTED_MEAN_STREAK","RR_WEIGHTED_MEAN_STREAK","WINBACK_CORP_WEIGHTED_MEAN_STREAK","DECEMBER_WEIGHTED_MEAN_STREAK","OTHER_WEIGHTED_MEAN_STREAK","AOAO_WEIGHTED_MEAN_STREAK","FOUNDER_WEIGHTED_MEAN_STREAK","FMF_WEIGHTED_MEAN_STREAK","NMF_WEIGHTED_MEAN_STREAK","KICK_START_WEIGHTED_MEAN_STREAK","FM_WEIGHTED_MEAN_STREAK","DSO_WEIGHTED_MEAN_STREAK","P65_WEIGHTED_MEAN_STREAK","CORP_WEIGHTED_MEAN_STREAK","WINBACK_WEIGHTED_MEAN_STREAK","FAO_WEIGHTED_MEAN_STREAK","SPRING_WEIGHTED_MEAN_STREAK"]

  increment_other_cols: ['CHRISTMAS_DAY','CHRISTMAS_DAY_OBSERVED','COLUMBUS_DAY','INDEPENDENCE_DAY','JUNETEENTH_NATIONAL_INDEPENDENCE_DAY','JUNETEENTH_NATIONAL_INDEPENDENCE_DAY_OBSERVED','LABOR_DAY','MARTIN_LUTHER_KING_JR_DAY','MEMORIAL_DAY','NEW_YEAR_S_DAY','NEW_YEAR_S_DAY_OBSERVED','THANKSGIVING_DAY','VETERANS_DAY','VETERANS_DAY_OBSERVED','WASHINGTON_S_BIRTHDAY']

validation :
  train_start_date : "2022-07-04"
  no_of_test_periods : 12
  metric : wmape

feature_selection :
  idv_column_name : "IDV"
  coefficient_value_column_name : "Value"
  intercept_feature_name : "Intercept"

  exogenous_variables:
      consider_correlation: no 
      uncertain_corr: ['TREND_YEAR','TREND_MONTH','TREND_QUARTER','CHRISTMAS_DAY','CHRISTMAS_DAY_OBSERVED','COLUMBUS_DAY','INDEPENDENCE_DAY','JUNETEENTH_NATIONAL_INDEPENDENCE_DAY','JUNETEENTH_NATIONAL_INDEPENDENCE_DAY_OBSERVED','LABOR_DAY','MARTIN_LUTHER_KING_JR_DAY','MEMORIAL_DAY','NEW_YEAR_S_DAY','NEW_YEAR_S_DAY_OBSERVED','THANKSGIVING_DAY','VETERANS_DAY','VETERANS_DAY_OBSERVED','WASHINGTON_S_BIRTHDAY']
      positive_corr: ["TOTAL_SPENDS_OVERALL","TOTAL_SPENDS_OVERALL_LAG1","TOTAL_SPENDS_OVERALL_LAG2","PRIMED_LEADS",'REGIONNAME_SI_WEEKLY',"PROMO_WEIGHTED_MEAN","SUMMER_WEIGHTED_MEAN","AOJO_WEIGHTED_MEAN","NEWVEMBER_WEIGHTED_MEAN","RR_WEIGHTED_MEAN","WINBACK_CORP_WEIGHTED_MEAN","DECEMBER_WEIGHTED_MEAN","OTHER_WEIGHTED_MEAN","AOAO_WEIGHTED_MEAN","FOUNDER_WEIGHTED_MEAN","FMF_WEIGHTED_MEAN","NMF_WEIGHTED_MEAN","KICK_START_WEIGHTED_MEAN","FM_WEIGHTED_MEAN","DSO_WEIGHTED_MEAN","P65_WEIGHTED_MEAN","CORP_WEIGHTED_MEAN","WINBACK_WEIGHTED_MEAN","FAO_WEIGHTED_MEAN","SPRING_WEIGHTED_MEAN",
                      "PROMO_WEIGHTED_MEAN_STREAK","SUMMER_WEIGHTED_MEAN_STREAK","AOJO_WEIGHTED_MEAN_STREAK","NEWVEMBER_WEIGHTED_MEAN_STREAK","RR_WEIGHTED_MEAN_STREAK","WINBACK_CORP_WEIGHTED_MEAN_STREAK","DECEMBER_WEIGHTED_MEAN_STREAK","OTHER_WEIGHTED_MEAN_STREAK","AOAO_WEIGHTED_MEAN_STREAK","FOUNDER_WEIGHTED_MEAN_STREAK","FMF_WEIGHTED_MEAN_STREAK","NMF_WEIGHTED_MEAN_STREAK","KICK_START_WEIGHTED_MEAN_STREAK","FM_WEIGHTED_MEAN_STREAK","DSO_WEIGHTED_MEAN_STREAK","P65_WEIGHTED_MEAN_STREAK","CORP_WEIGHTED_MEAN_STREAK","WINBACK_WEIGHTED_MEAN_STREAK","FAO_WEIGHTED_MEAN_STREAK","SPRING_WEIGHTED_MEAN_STREAK",
                     "FMF_ACTIVE_STUDIOS_NORMALIZED","NMF_ACTIVE_STUDIOS_NORMALIZED","FM_ACTIVE_STUDIOS_NORMALIZED","KICK_START_ACTIVE_STUDIOS_NORMALIZED","FOUNDER_ACTIVE_STUDIOS_NORMALIZED","RR_ACTIVE_STUDIOS_NORMALIZED","WINBACK_CORP_ACTIVE_STUDIOS_NORMALIZED","SUMMER_ACTIVE_STUDIOS_NORMALIZED","AOJO_ACTIVE_STUDIOS_NORMALIZED","NEWVEMBER_ACTIVE_STUDIOS_NORMALIZED","OTHER_ACTIVE_STUDIOS_NORMALIZED","AOAO_ACTIVE_STUDIOS_NORMALIZED","DSO_ACTIVE_STUDIOS_NORMALIZED","PROMO_ACTIVE_STUDIOS_NORMALIZED","P65_ACTIVE_STUDIOS_NORMALIZED","CORP_ACTIVE_STUDIOS_NORMALIZED","WINBACK_ACTIVE_STUDIOS_NORMALIZED","FAO_ACTIVE_STUDIOS_NORMALIZED","SPRING_ACTIVE_STUDIOS_NORMALIZED"]
      negative_corr: ["REGIONAL_CPI","REGIONAL_UNEMPLOYMENT_RATE","HPI"]
  lasso_scipy:
    consider_limits: yes
    zero_penalty_vars: ["PROMO_WEIGHTED_MEAN","SUMMER_WEIGHTED_MEAN","AOJO_WEIGHTED_MEAN","NEWVEMBER_WEIGHTED_MEAN","RR_WEIGHTED_MEAN","WINBACK_CORP_WEIGHTED_MEAN","DECEMBER_WEIGHTED_MEAN","OTHER_WEIGHTED_MEAN","AOAO_WEIGHTED_MEAN","FOUNDER_WEIGHTED_MEAN","FMF_WEIGHTED_MEAN","NMF_WEIGHTED_MEAN","KICK_START_WEIGHTED_MEAN","FM_WEIGHTED_MEAN","DSO_WEIGHTED_MEAN","P65_WEIGHTED_MEAN","CORP_WEIGHTED_MEAN","WINBACK_WEIGHTED_MEAN","FAO_WEIGHTED_MEAN","SPRING_WEIGHTED_MEAN",
                      "PROMO_WEIGHTED_MEAN_STREAK","SUMMER_WEIGHTED_MEAN_STREAK","AOJO_WEIGHTED_MEAN_STREAK","NEWVEMBER_WEIGHTED_MEAN_STREAK","RR_WEIGHTED_MEAN_STREAK","WINBACK_CORP_WEIGHTED_MEAN_STREAK","DECEMBER_WEIGHTED_MEAN_STREAK","OTHER_WEIGHTED_MEAN_STREAK","AOAO_WEIGHTED_MEAN_STREAK","FOUNDER_WEIGHTED_MEAN_STREAK","FMF_WEIGHTED_MEAN_STREAK","NMF_WEIGHTED_MEAN_STREAK","KICK_START_WEIGHTED_MEAN_STREAK","FM_WEIGHTED_MEAN_STREAK","DSO_WEIGHTED_MEAN_STREAK","P65_WEIGHTED_MEAN_STREAK","CORP_WEIGHTED_MEAN_STREAK","WINBACK_WEIGHTED_MEAN_STREAK","FAO_WEIGHTED_MEAN_STREAK","SPRING_WEIGHTED_MEAN_STREAK",
                     "FMF_ACTIVE_STUDIOS_NORMALIZED","NMF_ACTIVE_STUDIOS_NORMALIZED","FM_ACTIVE_STUDIOS_NORMALIZED","KICK_START_ACTIVE_STUDIOS_NORMALIZED","FOUNDER_ACTIVE_STUDIOS_NORMALIZED","RR_ACTIVE_STUDIOS_NORMALIZED","WINBACK_CORP_ACTIVE_STUDIOS_NORMALIZED","SUMMER_ACTIVE_STUDIOS_NORMALIZED","AOJO_ACTIVE_STUDIOS_NORMALIZED","NEWVEMBER_ACTIVE_STUDIOS_NORMALIZED","OTHER_ACTIVE_STUDIOS_NORMALIZED","AOAO_ACTIVE_STUDIOS_NORMALIZED","DSO_ACTIVE_STUDIOS_NORMALIZED","PROMO_ACTIVE_STUDIOS_NORMALIZED","P65_ACTIVE_STUDIOS_NORMALIZED","CORP_ACTIVE_STUDIOS_NORMALIZED","WINBACK_ACTIVE_STUDIOS_NORMALIZED","FAO_ACTIVE_STUDIOS_NORMALIZED","SPRING_ACTIVE_STUDIOS_NORMALIZED",
                        ]
    metric: wmape
    Hyperparameters:
      alpha: [0.1]
      lambda: [0.002915,
              0.005577,
              0.001,
              ]

future_forecast :
  no_of_future_periods : 6
  bootstrap_size_for_CI : 30

  trend_cols : ['TREND_YEAR','TREND_MONTH','TREND_QUARTER']
  zero_value_cols : ["TOTAL_SPENDS_OVERALL","TOTAL_SPENDS_OVERALL_LAG1","TOTAL_SPENDS_OVERALL_LAG2","PRIMED_LEADS",'REGIONNAME_SI_WEEKLY',"PROMO_WEIGHTED_MEAN","SUMMER_WEIGHTED_MEAN","AOJO_WEIGHTED_MEAN","NEWVEMBER_WEIGHTED_MEAN","RR_WEIGHTED_MEAN","WINBACK_CORP_WEIGHTED_MEAN","DECEMBER_WEIGHTED_MEAN","OTHER_WEIGHTED_MEAN","AOAO_WEIGHTED_MEAN","FOUNDER_WEIGHTED_MEAN","FMF_WEIGHTED_MEAN","NMF_WEIGHTED_MEAN","KICK_START_WEIGHTED_MEAN","FM_WEIGHTED_MEAN","DSO_WEIGHTED_MEAN","P65_WEIGHTED_MEAN","CORP_WEIGHTED_MEAN","WINBACK_WEIGHTED_MEAN","FAO_WEIGHTED_MEAN","SPRING_WEIGHTED_MEAN",
                      "PROMO_WEIGHTED_MEAN_STREAK","SUMMER_WEIGHTED_MEAN_STREAK","AOJO_WEIGHTED_MEAN_STREAK","NEWVEMBER_WEIGHTED_MEAN_STREAK","RR_WEIGHTED_MEAN_STREAK","WINBACK_CORP_WEIGHTED_MEAN_STREAK","DECEMBER_WEIGHTED_MEAN_STREAK","OTHER_WEIGHTED_MEAN_STREAK","AOAO_WEIGHTED_MEAN_STREAK","FOUNDER_WEIGHTED_MEAN_STREAK","FMF_WEIGHTED_MEAN_STREAK","NMF_WEIGHTED_MEAN_STREAK","KICK_START_WEIGHTED_MEAN_STREAK","FM_WEIGHTED_MEAN_STREAK","DSO_WEIGHTED_MEAN_STREAK","P65_WEIGHTED_MEAN_STREAK","CORP_WEIGHTED_MEAN_STREAK","WINBACK_WEIGHTED_MEAN_STREAK","FAO_WEIGHTED_MEAN_STREAK","SPRING_WEIGHTED_MEAN_STREAK",
                     "FMF_ACTIVE_STUDIOS_NORMALIZED","NMF_ACTIVE_STUDIOS_NORMALIZED","FM_ACTIVE_STUDIOS_NORMALIZED","KICK_START_ACTIVE_STUDIOS_NORMALIZED","FOUNDER_ACTIVE_STUDIOS_NORMALIZED","RR_ACTIVE_STUDIOS_NORMALIZED","WINBACK_CORP_ACTIVE_STUDIOS_NORMALIZED","SUMMER_ACTIVE_STUDIOS_NORMALIZED","AOJO_ACTIVE_STUDIOS_NORMALIZED","NEWVEMBER_ACTIVE_STUDIOS_NORMALIZED","OTHER_ACTIVE_STUDIOS_NORMALIZED","AOAO_ACTIVE_STUDIOS_NORMALIZED","DSO_ACTIVE_STUDIOS_NORMALIZED","PROMO_ACTIVE_STUDIOS_NORMALIZED","P65_ACTIVE_STUDIOS_NORMALIZED","CORP_ACTIVE_STUDIOS_NORMALIZED","WINBACK_ACTIVE_STUDIOS_NORMALIZED","FAO_ACTIVE_STUDIOS_NORMALIZED","SPRING_ACTIVE_STUDIOS_NORMALIZED"]
  si_cols : ['REGIONNAME_SI_WEEKLY']

qc_checks :
  actual_col : NO_OF_NEW_JOINEES
  predicted_base_col : FINAL_BASE
  tpr_col : PROMO_JOINS

  train_test_rsq_mape_check_needed : yes
  rsq_mape_check_needed : no

  rsq_cutoff : 0.4
  mapecutoff : 0.3
  overfit_cutoff : 0.15

  baseline_checks_act_pred_needed : yes
  no_of_inc_base_cutoff : 5

  baseline_check_mape_needed : yes
  baseline_mape_cutoff : 0.3

  corr_base_act_check_needed : no
  corr_cut_off : 0.7

  variance_in_base_check_needed : yes
  var_cut_off : 1

  base_trends_check_needed : yes
  trend_slope_cut_off : 0.1

  latest_q_base_check_needed : no
